package dao.XmlDAO.SaxParsers;

public enum HumanTagName {
    HUMANS,HUMAN,ID,NAME,SURNAME,PATRONYMIC,GENDER,HOMEADRESS,BIRTHDAY,PHONENUMBER,DEPARTMENTNAME,
    MEDICALWORKERS,MEDICALWORKER,DIPLOMAPROFESSION,WORKPHONENUMBER,UNIVERSITYNAME,UNIVERSITYENDED,
    DOCTORS,DOCTOR,CURRENTPOST,STARTEDWORKING,PATIENTSHEALED,
    HEADPHYSICIANS,HEADPHYSICIAN,ENDEDNWORKING,FUTUREPLANSFORHOSPITAL,
    NURSES,NURSE,INJECTIONSDID,PATIENTSSAVED,
    INTERNS,INTERN,INTERNSHIPSTARTED,INTERNSHIPDAYS,MISTAKESMADE,
    PATIENTS,PATIENT,WARDNUMBER,DISEASE
}
